/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AnimalsIndexRouteImport } from './routes/animals.index'
import { Route as AnimalsIdRouteImport } from './routes/animals.$id'
import { Route as AssessmentIdRouteImport } from './routes/assessment.$id'
import { Route as CasesIdRouteImport } from './routes/cases.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIndexRoute = AnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIdRoute = AnimalsIdRouteImport.update({
  id: '/animals/$id',
  path: '/animals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdRoute = AssessmentIdRouteImport.update({
  id: '/assessment/$id',
  path: '/assessment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/assessment/$id': typeof AssessmentIdRoute
  '/cases/$id': typeof CasesIdRoute
  '/animals/': typeof AnimalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/assessment/$id': typeof AssessmentIdRoute
  '/cases/$id': typeof CasesIdRoute
  '/animals': typeof AnimalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/assessment/$id': typeof AssessmentIdRoute
  '/cases/$id': typeof CasesIdRoute
  '/animals/': typeof AnimalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/report'
    | '/animals/$id'
    | '/assessment/$id'
    | '/cases/$id'
    | '/animals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/report'
    | '/animals/$id'
    | '/assessment/$id'
    | '/cases/$id'
    | '/animals'
  id:
    | '__root__'
    | '/'
    | '/report'
    | '/animals/$id'
    | '/assessment/$id'
    | '/cases/$id'
    | '/animals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportRoute: typeof ReportRoute
  AnimalsIdRoute: typeof AnimalsIdRoute
  AssessmentIdRoute: typeof AssessmentIdRoute
  CasesIdRoute: typeof CasesIdRoute
  AnimalsIndexRoute: typeof AnimalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/': {
      id: '/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AnimalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$id': {
      id: '/animals/$id'
      path: '/animals/$id'
      fullPath: '/animals/$id'
      preLoaderRoute: typeof AnimalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id': {
      id: '/assessment/$id'
      path: '/assessment/$id'
      fullPath: '/assessment/$id'
      preLoaderRoute: typeof AssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportRoute: ReportRoute,
  AnimalsIdRoute: AnimalsIdRoute,
  AssessmentIdRoute: AssessmentIdRoute,
  CasesIdRoute: CasesIdRoute,
  AnimalsIndexRoute: AnimalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
